using System.IO;
using System.Text;

/// <summary>
/// A custom text writer that redirects output to a <see cref="StringWriter"/> instance.
/// This class is specifically designed for capturing the output of Python scripts executed within Unity,
/// allowing the output to be used within Unity's C# environment.
/// </summary>
public class CustomTextWriter : TextWriter
{
    private StringWriter _stringWriter;

    public CustomTextWriter(StringWriter stringWriter)
    {
        _stringWriter = stringWriter;
    }

    public override Encoding Encoding => _stringWriter.Encoding;

    public override void Write(char value)
    {
        _stringWriter.Write(value);
    }

    public override void WriteLine(string value)
    {
        _stringWriter.WriteLine(value);
    }

    /// <summary>
    /// Writes a string to the <see cref="StringWriter"/>. This method is intended to be used by the Python runtime
    /// to capture output generated by Python scripts executed via <see cref="PythonEngine.Exec"/>.
    /// </summary>
    /// <param name="value">The string to write.</param>
    public void write(string value)
    {
        _stringWriter.Write(value);
    }
}